baseURL = "https://trai25.github.io/altnotes/"
publishDir = "docs"
languageCode = "zh-CN"
title = "alt.Notes"
theme = "paper"
preserveTaxonomyNames = true
paginate = 10
paginatePath = "page"
enableEmoji = true
